// KQL script
// Use management commands in this script to configure your database items, such as tables, functions, materialized views, and more.


.create-merge table Events_WS (type:string, ['time']:string, source:string, subject:string, specversion:string, dataschemaversion:string, id:string, datacontenttype:string, data:dynamic, EventProcessedUtcTime:datetime, PartitionId:long, EventEnqueuedUtcTime:datetime) 
.create-merge table Capacity_events (subject:string, specversion:string, source:string, ['time']:string, id:string, type:string, dataschemaversion:string, data:dynamic) 
.create-merge table CapacitySummaryEvents (Timestamp:datetime, CapacityId:string, CapacityName:string, Region:string, Sku:string, TotalCores:int, UsedCores:int, InteractiveDelayMs:real, InteractiveDelayThresholdMs:real, InteractiveDelayThresholdPercentage:real, BackgroundDelayMs:real, BackgroundDelayThresholdMs:real, BackgroundDelayThresholdPercentage:real, ThrottlingState:string, OverloadState:string, SmoothedUtilization:real, RawUtilization:real, EventType:string, RawJson:dynamic) 
